import pandas as pd
import requests
import time
import re
import os

# ==========================================
# 1. CONFIGURATION & CREDENTIALS
# ==========================================
MODE = "sync"

# Your Master API Key is required for writing contacts & managing sequences
APOLLO_API_KEY = "qHZgYECHVdxOrg4bb69-oQ"
SEQUENCE_ID = "6a1154f510c64c00105b527f"

# Optionally force a specific sender email (e.g., "parag@softwarebrio.com").
# If left as None, the script automatically picks your first active connected email account.
SENDER_EMAIL_OVERRIDE = "parag@softwarebrio.in"

# The CSV file generated by your Gemini outreach script
INPUT_CSV = "Generated_Emails_POC_Output_20260523_002947.csv"

# Apollo API Settings
BASE_URL = "https://api.apollo.io/api/v1"
HEADERS = {
    "x-api-key": APOLLO_API_KEY,
    "Content-Type": "application/json",
    "Cache-Control": "no-cache"
}

# Network request timeout in seconds to prevent the script from hanging on bad sockets
TIMEOUT_LIMIT = 15

# ==========================================
# 2. MAP YOUR CUSTOM SYSTEM KEYS HERE
# ==========================================
CUSTOM_FIELD_MAPPING = {
    "ai_subject": "6a11393994a700000c18d5d7",
    "ai_intro_body": "6a113bfd66051a0020267334",
    "ai_followup_1": "6a11396c0f6b9b0014ab1f2e",
    "ai_followup_2": "6a11397cc7797c001018996a"
}


# Helper to check if configuration placeholders are still default
def has_unmapped_placeholders():
    for val in CUSTOM_FIELD_MAPPING.values():
        if "your_apollo_" in str(val):
            return True
    return False


# Helper to validate email formatting locally to save API calls
def is_valid_email(email_str):
    if not email_str or pd.isna(email_str):
        return False
    pattern = r'^[^@\s]+@[^@\s]+\.[^@\s]+$'
    return bool(re.match(pattern, str(email_str).strip()))


# Sanitize a value from a pandas row: NaN and None become empty string.
# Apollo returns HTTP 422 if NaN appears in the JSON body.
def clean_val(v):
    if v is None:
        return ""
    try:
        if pd.isna(v):
            return ""
    except (TypeError, ValueError):
        pass
    return str(v).strip()


# ==========================================
# 3. GET CONNECTED SENDER INBOX ID
# ==========================================
def get_active_email_account_id():
    """
    Fetches connected email accounts from Apollo.
    Returns the ID of the active account to use for sending emails.
    """
    url = f"{BASE_URL}/email_accounts"
    print("[*] Retrieving connected email senders from Apollo...")

    try:
        response = requests.get(url, headers=HEADERS, timeout=TIMEOUT_LIMIT)
        if response.status_code == 200:
            accounts = response.json().get("email_accounts", [])
            active_accounts = [a for a in accounts if a.get("active") is True]

            if not active_accounts:
                print("[!] Error: No active connected email inboxes found in your Apollo account.")
                print("    Please connect an inbox under Apollo Settings > Channels > Email.")
                return None

            # If an override was requested, find it — fail hard so the user
            # knows immediately rather than sending from the wrong inbox.
            if SENDER_EMAIL_OVERRIDE:
                for acct in active_accounts:
                    if acct.get("email") == SENDER_EMAIL_OVERRIDE:
                        print(f"[+] Found overridden sender inbox: {acct.get('email')} (ID: {acct.get('id')})")
                        return acct.get("id")
                available = [a.get("email") for a in active_accounts]
                print(f"[!] Error: SENDER_EMAIL_OVERRIDE '{SENDER_EMAIL_OVERRIDE}' was not found among active inboxes.")
                print(f"    Active inboxes: {available}")
                print(f"    Either correct the override or set SENDER_EMAIL_OVERRIDE = None to auto-select.")
                return None

            # Default to the first active email account
            selected = active_accounts[0]
            print(f"[+] Selected active sender: {selected.get('email')} (ID: {selected.get('id')})")
            return selected.get("id")
        else:
            print(f"[-] Failed to fetch email accounts: {response.text}")
    except Exception as e:
        print(f"[!] Error checking email accounts: {str(e)}")

    return None


# ==========================================
# 4. RUN DIAGNOSTIC: GET CUSTOM FIELDS
# ==========================================
def run_custom_fields_diagnostic():
    url = f"{BASE_URL}/typed_custom_fields"
    print("\n[*] Fetching custom fields from Apollo...")

    try:
        response = requests.get(url, headers=HEADERS, timeout=TIMEOUT_LIMIT)
        if response.status_code == 200:
            fields_data = response.json()
            custom_fields = fields_data.get("typed_custom_fields", [])

            print(f"\n[+] Success! Found {len(custom_fields)} custom fields on your account.")
            print("-" * 60)
            print(f"{'Field Label':<25} | {'Apollo Internal API Key':<35}")
            print("-" * 60)

            for field in custom_fields:
                label = field.get("name", "Unknown")
                raw_key = field.get("id", "Unknown")
                print(f"{label:<25} | {raw_key:<35}")
            print("-" * 60)
            print("[*] Copy these keys and insert them into the CUSTOM_FIELD_MAPPING dict.")

        else:
            print(f"[-] Diagnostic failed with status {response.status_code}: {response.text}")
    except Exception as e:
        print(f"[!] Error running diagnostic: {str(e)}")


# ==========================================
# 5. CONTACT SYNC & SEQUENCE ENROLLMENT
# ==========================================
def find_existing_contact_by_email(email):
    """
    Returns the contact ID only if Apollo has a contact whose email field
    exactly matches the supplied address.  The /contacts/search endpoint uses
    a full-text keyword index, so results may include unrelated contacts whose
    names or companies happen to contain similar text.  We filter the response
    down to an exact email match to avoid patching the wrong record.
    """
    url = f"{BASE_URL}/contacts/search"
    payload = {"q_keywords": email, "per_page": 25}

    def _search():
        resp = requests.post(url, json=payload, headers=HEADERS, timeout=TIMEOUT_LIMIT)
        if resp.status_code == 200:
            for contact in resp.json().get("contacts", []):
                # Check every email slot Apollo stores for this contact
                contact_emails = [contact.get("email", "")] + [
                    e.get("email", "") for e in contact.get("contact_emails", [])
                ]
                if email.lower() in [e.lower() for e in contact_emails if e]:
                    return contact.get("id")
        return None

    try:
        return _search()
    except requests.exceptions.Timeout:
        print(f"[!] Warning: Search timed out for {email}. Retrying once...")
        time.sleep(2)
        try:
            return _search()
        except Exception:
            pass
    except Exception as e:
        print(f"[!] Search error for {email}: {str(e)}")
    return None


def sync_to_apollo(lead_data, email_account_id):
    raw_email = lead_data.get("Email ID")

    if not is_valid_email(raw_email):
        print(f"[-] Skipping lead: Invalid email format '{raw_email}'")
        return False

    email = str(raw_email).strip()
    name = clean_val(lead_data.get("Reviewer Name"))
    first_name = name.split()[0] if name else "There"
    last_name = " ".join(name.split()[1:]) if name else ""

    # All values from pandas must be sanitized — empty cells arrive as float('nan')
    # which produces invalid JSON and causes Apollo to return HTTP 422.
    typed_custom_fields = {
        CUSTOM_FIELD_MAPPING["ai_subject"]:    clean_val(lead_data.get("Intro_Subject")),
        CUSTOM_FIELD_MAPPING["ai_intro_body"]: clean_val(lead_data.get("Intro_Body")),
        CUSTOM_FIELD_MAPPING["ai_followup_1"]: clean_val(lead_data.get("Generated_Followup_1")),
        CUSTOM_FIELD_MAPPING["ai_followup_2"]: clean_val(lead_data.get("Generated_Followup_2")),
    }

    contact_id = None
    existing_id = find_existing_contact_by_email(email)

    if existing_id:
        print(f"[*] Contact {email} already exists (ID: {existing_id}). Patching custom fields...")
        # Only send fields we want to update — don't resend email or name to avoid collisions.
        patch_payload = {
            "first_name": first_name,
            "last_name": last_name,
            "organization_name": clean_val(lead_data.get("Reviewer Company")),
            "typed_custom_fields": typed_custom_fields,
        }
        update_url = f"{BASE_URL}/contacts/{existing_id}"
        update_response = requests.patch(update_url, json=patch_payload, headers=HEADERS, timeout=TIMEOUT_LIMIT)

        if update_response.status_code == 200:
            contact_id = existing_id
            print(f"[+] Successfully patched existing contact.")
        else:
            print(f"[-] Failed to patch contact {existing_id}: {update_response.status_code} — {update_response.text}")
    else:
        print(f"[*] Creating new contact for {email}...")
        create_payload = {
            "email": email,
            "first_name": first_name,
            "last_name": last_name,
            "organization_name": clean_val(lead_data.get("Reviewer Company")),
            "typed_custom_fields": typed_custom_fields,
            # Prevent Apollo from silently creating a second record for the same address
            "run_dedupe": True,
        }
        create_url = f"{BASE_URL}/contacts"
        create_response = requests.post(create_url, json=create_payload, headers=HEADERS, timeout=TIMEOUT_LIMIT)

        if create_response.status_code == 200:
            contact_id = create_response.json().get("contact", {}).get("id")
            print(f"[+] Successfully created new contact (ID: {contact_id}).")
        else:
            print(f"[-] Failed to create contact: {create_response.status_code} — {create_response.text}")

    if not contact_id:
        return False

    # Enroll the contact into the sequence
    sequence_url = f"{BASE_URL}/emailer_campaigns/{SEQUENCE_ID}/add_contact_ids"
    sequence_payload = {
        "contact_ids": [contact_id],
        "emailer_campaign_id": SEQUENCE_ID,
        "send_email_from_email_account_id": email_account_id,
        "async": False,
    }
    query_params = {
        "sequence_unverified_email": "true",
        "sequence_active_in_other_campaigns": "true",
        "sequence_finished_in_other_campaigns": "true",
    }

    seq_response = requests.post(
        sequence_url,
        json=sequence_payload,
        params=query_params,
        headers=HEADERS,
        timeout=TIMEOUT_LIMIT,
    )

    if seq_response.status_code == 200:
        body = seq_response.json()
        enrolled = body.get("contact_ids", [])
        skipped = body.get("skipped_contact_ids", [])

        if contact_id in skipped:
            reason = next(
                (s.get("reason", "unknown") for s in body.get("skipped_contacts", [])
                 if s.get("id") == contact_id),
                "unknown"
            )
            print(f"[~] Contact {contact_id} was skipped by Apollo: {reason}")
            # Custom fields were still patched above, so this is non-fatal.
            return True

        if contact_id in enrolled or enrolled:
            print(f"[+] Enrolled contact {contact_id} in sequence {SEQUENCE_ID}.")
            return True

        print(f"[~] Enrollment response did not confirm contact {contact_id}: {body}")
        return True  # 200 response — treat as success
    else:
        print(f"[-] Sequence enrollment failed: {seq_response.status_code} — {seq_response.text}")
        return False


# ==========================================
# 6. MAIN PIPELINE
# ==========================================
def main():
    if MODE == "diagnostic":
        run_custom_fields_diagnostic()

    elif MODE == "sync":
        # Safeguard to prevent execution with default placeholder mapping keys
        if has_unmapped_placeholders():
            print("[!] Halting execution: Your CUSTOM_FIELD_MAPPING contains default placeholders.")
            print("    Please switch MODE to 'diagnostic' first, run the script, retrieve your")
            print("    system's custom field keys, and map them in the dictionary before running sync.")
            return

        # Fetch the active email account sender ID to resolve the email parameter error
        email_account_id = get_active_email_account_id()
        if not email_account_id:
            print("[!] Halting execution: Active sender email account ID could not be resolved.")
            return

        if not os.path.exists(INPUT_CSV):
            print(f"[!] Error: Could not locate the CSV file at {INPUT_CSV}")
            return

        print(f"[*] Loading CSV file: {INPUT_CSV}")
        df = pd.read_csv(INPUT_CSV)

        df_filtered = df.dropna(subset=['Email ID']).copy()
        print(f"[*] Found {len(df_filtered)} leads to process. Commencing Apollo sync...")

        success_count = 0
        for index, row in df_filtered.iterrows():
            lead_info = row.to_dict()
            print(f"\nProcessing Lead ({index + 1}/{len(df_filtered)}): {lead_info.get('Email ID')}")

            success = sync_to_apollo(lead_info, email_account_id)
            if success:
                success_count += 1

            time.sleep(1)

        print(f"\n[+] Apollo sync completed! Successful uploads/updates: {success_count}/{len(df_filtered)}")


if __name__ == "__main__":
    main()