import pandas as pd
import requests
import json
import time
import re
import os

# ==========================================
# 1. CONFIGURATION & CREDENTIALS
# ==========================================
MODE = "sync"

# Your Master API Key is required for writing contacts & managing sequences
APOLLO_API_KEY = "qHZgYECHVdxOrg4bb69-oQ"
SEQUENCE_ID = "6a1154f510c64c00105b527f"

# Optionally force a specific sender email (e.g., "parag@softwarebrio.com").
# If left as None, the script automatically picks your first active connected email account.
SENDER_EMAIL_OVERRIDE = "parag@softwarebrio.in"

# The CSV file generated by your Gemini outreach script
INPUT_CSV = "Generated_Emails_POC_Output_20260523_002947.csv"

# Apollo API Settings
BASE_URL = "https://api.apollo.io/api/v1"
HEADERS = {
    "x-api-key": APOLLO_API_KEY,
    "Content-Type": "application/json",
    "Cache-Control": "no-cache"
}

# Network request timeout in seconds to prevent the script from hanging on bad sockets
TIMEOUT_LIMIT = 15

# ==========================================
# 2. MAP YOUR CUSTOM SYSTEM KEYS HERE
# ==========================================
CUSTOM_FIELD_MAPPING = {
    "ai_subject": "6a11393994a700000c18d5d7",
    "ai_intro_body": "6a113bfd66051a0020267334",
    "ai_followup_1": "6a11396c0f6b9b0014ab1f2e",
    "ai_followup_2": "6a11397cc7797c001018996a"
}


# Helper to check if configuration placeholders are still default
def has_unmapped_placeholders():
    for val in CUSTOM_FIELD_MAPPING.values():
        if "your_apollo_" in str(val):
            return True
    return False


# Helper to validate email formatting locally to save API calls
def is_valid_email(email_str):
    if not email_str or pd.isna(email_str):
        return False
    # Simple regex to check standard email format
    pattern = r'^[^@\s]+@[^@\s]+\.[^@\s]+$'
    return bool(re.match(pattern, str(email_str).strip()))


# ==========================================
# 3. GET CONNECTED SENDER INBOX ID
# ==========================================
def get_active_email_account_id():
    """
    Fetches connected email accounts from Apollo.
    Returns the ID of the active account to use for sending emails.
    """
    url = f"{BASE_URL}/email_accounts"
    print("[*] Retrieving connected email senders from Apollo...")

    try:
        response = requests.get(url, headers=HEADERS, timeout=TIMEOUT_LIMIT)
        if response.status_code == 200:
            accounts = response.json().get("email_accounts", [])
            active_accounts = [a for a in accounts if a.get("active") is True]

            if not active_accounts:
                print("[!] Error: No active connected email inboxes found in your Apollo account.")
                print("    Please connect an inbox under Apollo Settings > Channels > Email.")
                return None

            # If an override was requested, find it
            if SENDER_EMAIL_OVERRIDE:
                for acct in active_accounts:
                    if acct.get("email") == SENDER_EMAIL_OVERRIDE:
                        print(f"[+] Found overridden sender inbox: {acct.get('email')} (ID: {acct.get('id')})")
                        return acct.get("id")

            # Default to the first active email account
            selected = active_accounts[0]
            print(f"[+] Selected active sender: {selected.get('email')} (ID: {selected.get('id')})")
            return selected.get("id")
        else:
            print(f"[-] Failed to fetch email accounts: {response.text}")
    except Exception as e:
        print(f"[!] Error checking email accounts: {str(e)}")

    return None


# ==========================================
# 4. RUN DIAGNOSTIC: GET CUSTOM FIELDS
# ==========================================
def run_custom_fields_diagnostic():
    url = f"{BASE_URL}/typed_custom_fields"
    print("\n[*] Fetching custom fields from Apollo...")

    try:
        response = requests.get(url, headers=HEADERS, timeout=TIMEOUT_LIMIT)
        if response.status_code == 200:
            fields_data = response.json()
            custom_fields = fields_data.get("typed_custom_fields", [])

            print(f"\n[+] Success! Found {len(custom_fields)} custom fields on your account.")
            print("-" * 60)
            print(f"{'Field Label':<25} | {'Apollo Internal API Key':<35}")
            print("-" * 60)

            for field in custom_fields:
                label = field.get("name", "Unknown")
                raw_key = field.get("id", "Unknown")
                print(f"{label:<25} | {raw_key:<35}")
            print("-" * 60)
            print("[*] Copy these keys and insert them into the CUSTOM_FIELD_MAPPING dict.")

        else:
            print(f"[-] Diagnostic failed with status {response.status_code}: {response.text}")
    except Exception as e:
        print(f"[!] Error running diagnostic: {str(e)}")


# ==========================================
# 5. CONTACT SYNC & SEQUENCE ENROLLMENT
# ==========================================
def find_existing_contact_by_email(email):
    url = f"{BASE_URL}/contacts/search"
    payload = {"q_keywords": email}

    try:
        response = requests.post(url, json=payload, headers=HEADERS, timeout=TIMEOUT_LIMIT)
        if response.status_code == 200:
            contacts = response.json().get("contacts", [])
            if contacts:
                return contacts[0].get("id")
    except requests.exceptions.Timeout:
        print(f"[!] Warning: Search request timed out for email {email}. Retrying once...")
        time.sleep(2)
        try:
            response = requests.post(url, json=payload, headers=HEADERS, timeout=TIMEOUT_LIMIT)
            if response.status_code == 200:
                contacts = response.json().get("contacts", [])
                if contacts:
                    return contacts[0].get("id")
        except Exception:
            pass
    except Exception as e:
        print(f"[!] Search error for email {email}: {str(e)}")
    return None


def sync_to_apollo(lead_data, email_account_id):
    raw_email = lead_data.get("Email ID")

    # Pre-validate email format locally
    if not is_valid_email(raw_email):
        print(f"[-] Skipping lead: Invalid email format '{raw_email}'")
        return False

    email = str(raw_email).strip()
    name = str(lead_data.get("Reviewer Name", "")).strip()
    first_name = name.split()[0] if name else "There"
    last_name = " ".join(name.split()[1:]) if name else ""

    # FIXED: Replaced "custom_fields" with "typed_custom_fields" to resolve Issue 1
    contact_payload = {
        "email": email,
        "first_name": first_name,
        "last_name": last_name,
        "organization_name": lead_data.get("Reviewer Company"),
        "typed_custom_fields": {
            CUSTOM_FIELD_MAPPING["ai_subject"]: lead_data.get("Intro_Subject"),
            CUSTOM_FIELD_MAPPING["ai_intro_body"]: lead_data.get("Intro_Body"),
            CUSTOM_FIELD_MAPPING["ai_followup_1"]: lead_data.get("Generated_Followup_1"),
            CUSTOM_FIELD_MAPPING["ai_followup_2"]: lead_data.get("Generated_Followup_2")
        }
    }

    contact_id = None
    existing_id = find_existing_contact_by_email(email)

    if existing_id:
        print(f"[*] Contact {email} already exists (ID: {existing_id}). Updating fields...")
        update_url = f"{BASE_URL}/contacts/{existing_id}"
        # Contact updates require PATCH according to documentation guidelines
        update_response = requests.patch(update_url, json=contact_payload, headers=HEADERS, timeout=TIMEOUT_LIMIT)

        if update_response.status_code == 200:
            contact_id = existing_id
            print(f"[+] Successfully updated existing contact.")
        else:
            print(f"[-] Failed to update contact: {update_response.text}")
    else:
        print(f"[*] Creating new contact for {email}...")
        create_url = f"{BASE_URL}/contacts"
        create_response = requests.post(create_url, json=contact_payload, headers=HEADERS, timeout=TIMEOUT_LIMIT)

        if create_response.status_code == 200:
            contact_id = create_response.json().get("contact", {}).get("id")
            print(f"[+] Successfully created new contact (ID: {contact_id}).")
        else:
            print(f"[-] Failed to create contact: {create_response.text}")

    # Enroll the contact into the sequence
    if contact_id:
        # Endpoint matching schema definition
        sequence_url = f"{BASE_URL}/emailer_campaigns/{SEQUENCE_ID}/add_contact_ids"

        # REQUIRED query/body payloads
        sequence_payload = {
            "contact_ids": [contact_id],
            "emailer_campaign_id": SEQUENCE_ID,
            "send_email_from_email_account_id": email_account_id,
            "async": False
        }

        # ADDED Query parameters from OpenAPI definition to bypass deliverability/sequence constraints
        query_params = {
            "sequence_unverified_email": "true",  # Force add unverified emails
            "sequence_active_in_other_campaigns": "true",  # Bypass other active sequence locks
            "sequence_finished_in_other_campaigns": "true"  # Bypass finished sequence locks
        }

        seq_response = requests.post(
            sequence_url,
            json=sequence_payload,
            params=query_params,  # Pass query overrides
            headers=HEADERS,
            timeout=TIMEOUT_LIMIT
        )

        if seq_response.status_code == 200:
            print(f"[+] Enrolled contact {contact_id} in Sequence {SEQUENCE_ID}.")
            return True
        else:
            print(f"[-] Enrollment failed: {seq_response.text}")

    return False


# ==========================================
# 6. MAIN PIPELINE
# ==========================================
def main():
    if MODE == "diagnostic":
        run_custom_fields_diagnostic()

    elif MODE == "sync":
        # Safeguard to prevent execution with default placeholder mapping keys
        if has_unmapped_placeholders():
            print("[!] Halting execution: Your CUSTOM_FIELD_MAPPING contains default placeholders.")
            print("    Please switch MODE to 'diagnostic' first, run the script, retrieve your")
            print("    system's custom field keys, and map them in the dictionary before running sync.")
            return

        # Fetch the active email account sender ID to resolve the email parameter error
        email_account_id = get_active_email_account_id()
        if not email_account_id:
            print("[!] Halting execution: Active sender email account ID could not be resolved.")
            return

        if not os.path.exists(INPUT_CSV):
            print(f"[!] Error: Could not locate the CSV file at {INPUT_CSV}")
            return

        print(f"[*] Loading CSV file: {INPUT_CSV}")
        df = pd.read_csv(INPUT_CSV)

        df_filtered = df.dropna(subset=['Email ID']).copy()
        print(f"[*] Found {len(df_filtered)} leads to process. Commencing Apollo sync...")

        success_count = 0
        for index, row in df_filtered.iterrows():
            lead_info = row.to_dict()
            print(f"\nProcessing Lead ({index + 1}/{len(df_filtered)}): {lead_info.get('Email ID')}")

            success = sync_to_apollo(lead_info, email_account_id)
            if success:
                success_count += 1

            time.sleep(1)

        print(f"\n[+] Apollo sync completed! Successful uploads/updates: {success_count}/{len(df_filtered)}")


if __name__ == "__main__":
    main()